### ISSUE TITLE
CSS Code changes

### ISSUE THREAD

**Issue by fishenjoe** [Pos3ydon/saufgame.online#1]
Change:
1. px to em 
2. vh to %
```css
body {
    width: 100vw;
    height: 100vh;
    background-color: #001828;
    margin: 0;
    padding: 0;
    overflow: hidden;
    position: absolute;
    top: 0;
}
``` 
3. padding px/% to em 
```css
.sidebarButton {
    font-family: particle;
    font-size: 20px; <-- to em
    letter-spacing: 4px; <-- to em
    cursor: pointer;
    text-align: left;
    padding: 5% 0; <-- to em
    padding-left: 10%; <-- to em
    width: 90%;
    transition: all .60s;
    -moz-user-select: none;
    -khtml-user-select: none;
    -webkit-user-select: none;
}
```
